env:
  browser: true
  es6: true
  node: true
extends: 'airbnb'
parserOptions:
  sourceType: module
rules:
  indent:
    - warn
    - 2
  linebreak-style:
    - error
    - unix
    - windows
  no-underscore-dangle: off
  no-param-reassign:
    - error
    - props: false
  object-shorthand:
    - 2
    - consistent
  semi:
    - warn
    - always
  valid-jsdoc:
    - warn
